[package]
name = "truist-api"
version = "0.1.0"
authors = ["Bradley Shawyer <21098019+bradleyess@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
